root@e165a7:~/mstackx/examples/guestbook# cat staging-autoscale.yaml
apiVersion: v1
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: frontend
    namespace: staging
  spec:
    maxReplicas: 6
    minReplicas: 3
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: frontend
    targetCPUUtilizationPercentage: 50
  status:
    currentCPUUtilizationPercentage: 1
    currentReplicas: 3
    desiredReplicas: 3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
root@e165a7:~/mstackx/examples/guestbook#